name: Cloud Resume API Challenge

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DYNAMODB_TABLE_NAME: ${{ secrets.TABLE_NAME }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0 

    - name: Terraform Destroy
      id: destroy
      run: terraform destroy -auto-approve

    # - name: Initialize Terraform
    #   id: init
    #   run: terraform init
    #   working-directory: infra

    # - name: Validate Terraform configuration
    #   run: terraform validate
    #   id: validate
    #   working-directory: infra

    # - name: Plan Terraform deployment
    #   id: plan
    #   run: terraform plan -out=tfplan -input=false
    #   working-directory: infra
      
    # - name: Apply Terraform deployment
    #   id: apply
    #   run: terraform apply -auto-approve
    #   working-directory: infra

    - name: Upload JSON data to DynamoDB
      run: |
        aws dynamodb put-item \
          --table-name ${{ secrets.TABLE_NAME }} \
          --item file://files/resume.json \
          --region ${{ secrets.AWS_REGION }}
