name: Cloud Resume API Challenge

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DYNAMODB_TABLE_NAME: ${{secrets.TABLE_NAME}}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.0
    - name: Configure AWS credentials
      run: |
        echo "access_key = \"${AWS_ACCESS_KEY_ID}\"" >> terraform.tfvars
        echo "secret_key = \"${AWS_SECRET_ACCESS_KEY}\"" >> terraform.tfvars
        echo "region = \"${AWS_REGION}\"" >> terraform.tfvars

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform configuration
      run: terraform validate

    - name: Plan Terraform deployment
      run: terraform plan -out=tfplan -input=false
      
    - name: Apply Terraform deployment
      run: terraform apply -auto-approve tfplan -input=false

    - name: Put DynamoDB Item
      uses: mooyoul/dynamodb-actions@v1.2.1
      with:
        operation: batch-put
        region: ${{ env.AWS_REGION }}
        table: ${{ env.DYNAMODB_TABLE_NAME }}
        files: files/resume.json
