name: Cloud Resume API Challenge

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DYNAMODB_TABLE_NAME: ${{ secrets.TABLE_NAME }}
      BUCKET: ${{ secrets.BUCKET_NAME }}
      DIST: dist
      DIST_ID: ${{ secrets.ID }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_WORKSPACE: terraform-github-actions
      CONFIG_DIRECTORY: ./infra

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm ci
      working-directory: resume

    - name: Build Static Website
      run: npm run build
      working-directory: resume

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: |
        export TF_API_TOKEN=${{ secrets.TF_API_TOKEN }}
        terraform init
      working-directory: ${{ env.CONFIG_DIRECTORY }}

    - name: Terraform Plan
      run: |
        export TF_API_TOKEN=${{ secrets.TF_API_TOKEN }}
        terraform plan -out=tfplan
      working-directory: ${{ env.CONFIG_DIRECTORY }}

    - name: Terraform Apply
      run: |
        export TF_API_TOKEN=${{ secrets.TF_API_TOKEN }}
        terraform apply -auto-approve tfplan
      working-directory: ${{ env.CONFIG_DIRECTORY }}

    - name: Upload JSON Data to DynamoDB
      run: |
        aws dynamodb put-item \
          --table-name ${{ secrets.TABLE_NAME }} \
          --item file://files/resume.json \
          --region ${{ secrets.AWS_REGION }}

    - name: Copy files to the production resume website with the AWS CLI
      run: |
        aws s3 sync ${{ env.DIST }} s3://${{ env.BUCKET }} --delete
        aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths "/*"
